### PR TITLE
Have Tester return 0 if all tests passed, 1 if any test failed

### PR DESCRIPTION
**Pull request by kylemclean**
This should be useful for CI.

### CODE REVIEW

**Review by kuzi117 — CHANGES_REQUESTED** [review]
This would be better if the functions returned `bool` instead of `int` and then at the end did the ternary `return failed ? 1 : 0`. If you don't want to put extra effort into this (which I would totally understand) don't worry about it and I'll make the change myself.

**Comment by kylemclean** [comment]
> This would be better if the functions returned `bool` instead of `int` and then at the end did the ternary `return failed ? 1 : 0`. If you don't want to put extra effort into this (which I would totally understand) don't worry about it and I'll make the change myself.

Seems like a simple enough change. I'll do this.

**Comment by kuzi117** [comment]
I just added a contributors file to your branch, if that's ok with you. If you accept I'll accept the pull request.

**Comment by kylemclean** [comment]
> I just added a contributors file to your branch, if that's ok with you. If you accept I'll accept the pull request.

Yes, that's good. Thanks.

**Pull request merged**
