### PR TITLE
c++17 upgrade

### PR DESCRIPTION
**Pull request by rcunrau**
Make the tester work with C++17

### CODE REVIEW

**Review by quinnlp — COMMENTED** [review]
lgtm as long as it builds and runs on a ualberta machine.

**Comment by kuzi117** [comment]
Re: d7342a7c70f283da18a98c2cad6b1b4a2c8bff53
Any chance this is already addressed in a newer version of of this header? Just get it from the original repository, assuming the interface is the same. I'd prefer to replace it wholesale than to just `#if 0` parts that were probably added for a reason.

**Comment by kuzi117** [comment]
LGTM, bar the changes in the JSON header. If newer versions are extremely incompatible in interface (I don't know what's changed about JSON that would necessitate that) then it's probably fine to keep those changes. Otherwise I'm just hoping a better version supporters C++17 (or 20).

**Comment by quinnlp** [comment]
Thanks Braedy, good point!

@rcunrau here is the most recent release version of this file (v3.11.2) https://github.com/nlohmann/json/blob/v3.11.2/include/nlohmann/json.hpp

Could you try the tester with the updated version?

**Comment by rcunrau** [comment]
I tried compiling with the new json.hpp. It didn't work because of this refactoring:

#include <nlohmann/adl_serializer.hpp>
#include <nlohmann/byte_container_with_subtype.hpp>
#include <nlohmann/detail/conversions/from_json.hpp>
#include <nlohmann/detail/conversions/to_json.hpp>
#include <nlohmann/detail/exceptions.hpp>
#include <nlohmann/detail/hash.hpp>
#include <nlohmann/detail/input/binary_reader.hpp>
#include <nlohmann/detail/input/input_adapters.hpp>
#include <nlohmann/detail/input/lexer.hpp>
#include <nlohmann/detail/input/parser.hpp>
#include <nlohmann/detail/iterators/internal_iterator.hpp>
#include <nlohmann/detail/iterators/iter_impl.hpp>
#include <nlohmann/detail/iterators/iteration_proxy.hpp>
#include <nlohmann/detail/iterators/json_reverse_iterator.hpp>
#include <nlohmann/detail/iterators/primitive_iterator.hpp>
#include <nlohmann/detail/json_pointer.hpp>
#include <nlohmann/detail/json_ref.hpp>
#include <nlohmann/detail/macro_scope.hpp>
#include <nlohmann/detail/string_concat.hpp>
#include <nlohmann/detail/string_escape.hpp>
#include <nlohmann/detail/meta/cpp_future.hpp>
#include <nlohmann/detail/meta/type_traits.hpp>
#include <nlohmann/detail/output/binary_writer.hpp>
#include <nlohmann/detail/output/output_adapters.hpp>
#include <nlohmann/detail/output/serializer.hpp>
#include <nlohmann/detail/value_t.hpp>
#include <nlohmann/json_fwd.hpp>
#include <nlohmann/ordered_map.hpp>

Presumably we could include these 50 files, and the 100 they include, and then we'd be good to go :-)

**Comment by rcunrau** [comment]
I can certainly make the existing json.hpp less ugly. WRT the static_assert, does anyone know if it's important? Is it worth trying to make it work?

**Comment by kuzi117** [comment]
You need the single include version [here](https://github.com/nlohmann/json/blob/v3.11.2/single_include/nlohmann/json.hpp), not the separated out version. That should have everything you need in it...

**Comment by kuzi117** [comment]
I'm going to assume from the new commits that the new file resolved the issues. Full approval from me then, not that I really can claim ownership over this anymore 😂

**Comment by rcunrau** [comment]
You saved us! Thanks :-)

**Review by quinnlp — APPROVED** [review]

**Pull request merged**
