### PR TITLE
Meimar/refactor

### PR DESCRIPTION
**Pull request by JustinMeimar**
First of all, I apologize in advance for the messy diff. These changes should have been broken into 5-6 separate PRs. To compensate, I'll try to categorize the updates here.

1. Introduce the notation of a `testfile` which allows `stdin` and `stdout` to be supplied in comment directives from within the testcase itself. This relieved strict symmetry between `input` `output` and `input-stream` directories. More details on the semantics of a testfile can be found in the updated `README.md`.

2. Configure the tester to test itself. Thanks to Ron for setting this up. We set up an LLVM config
that compiles C programs and verifies the expected output. This lets us test how newlines and space diffs are handled, directives parsed etc. There are also some grader tests and runtime tests.

3. Grader. Since we are adding performance tests this semester a new table in the grader spreadsheet
had to be created. Unfortunately I failed to amend the grader as it was, so I resorted to re-writing the CSV generation in python.

4. For running an `llc` tool chain some extra magic parameters `$RT_PATH` and `$RT_LIB` were introduced. The motivation was due to `llc` tool chains giving much more stable timings for performance testing than `lli`

5. Collect timings from each test run.

6. Make error test parsing more lenient. We don't enforce the type of error due to an inherit ambiguity over which error should be thrown if a single line contains multiple errors. (Depends on the pass order)
```
procedure foo(character c1, character c2);

vector v1 = 1..10;

foo(v1[2], v1[5]); # should this line be an alias error or a type error? Depends on pass order.
```

5. Separate `stdout` and `stderr`. Previously there was ways to sploof the tester into thinking it
was running an error testcase.
```
"FakeError on line 9" -> std_output;
```

Please let me know any suggested improvements.

### CODE REVIEW

**Comment by JustinMeimar** [comment]
As for ensuring MacOS compatibility, the current [Gazprea Solution](https://github.com/cmput415/Gazprea24Solution) passes  all 1041 tests on main with
``tester ./llcConfig.json --timeout 10``
 
If this works on MacOS then the runtime exec stuff in `Command.cpp` works as expected. If either Mac users @rcunrau or @quinnlp could spare a few minutes to replicate the test it would be much apprecaited :D

**Comment by quinnlp** [comment]
I tried running the current Gazprea Solution on my mac. Initially, I got a lot of errors. The following tester patch fixes most of the errors:
```diff
diff --git a/src/toolchain/Command.cpp b/src/toolchain/Command.cpp
index e6cfc2a..7e12686 100644
--- a/src/toolchain/Command.cpp
+++ b/src/toolchain/Command.cpp
@@ -353,6 +353,10 @@ std::string stripLibraryName(const std::string& filename) {
   if (pos != std::string::npos) {
     result = result.substr(0, pos);
   }
+  pos = result.find(".dylib");
+  if (pos != std::string::npos) {
+    result = result.substr(0, pos);
+  }
   return result;
 }

```

When I ran the tests with the patched tester I saw 1 error:
```
quinnpham@Quinns-MacBook-Pro tests % tester -vv --debug-package=testfiles/regression_tests/reals/ llcConfig.json
Test Information:

Package: debugPkg (1 subpackages)
 - Subpackage: debugSubPackage (1 tests)
Total Packages: 1


Testing executable: solution -> "../bin/gazc"
With toolchain: gazprea-llc -> [gazprea, llc, clang, run]
Entering package: debugPkg
  Entering subpackage: debugSubPackage
----- TestFile: "inf.test"
procedure main() returns integer {
    real x = 19E56;
    real y = 87E45;

    x -> std_output;
    '\n' -> std_output;

    y -> std_output;
    '\n' -> std_output;

    x + y -> std_output;
    '\n' -> std_output;

    x / y -> std_output;
    '\n' -> std_output;

    x % y -> std_output;
    '\n' -> std_output;

    x - y -> std_output;
    '\n' -> std_output;

    x * y -> std_output;
    '\n' -> std_output;

    x ^ y -> std_output;
    '\n' -> std_output;

    -x -> std_output;
    '\n' -> std_output;

    +x -> std_output;
    '\n' -> std_output;

    x == y -> std_output;
    '\n' -> std_output;

    x != y -> std_output;
    '\n' -> std_output;

    x < y -> std_output;
    '\n' -> std_output;

    x > y -> std_output;
    '\n' -> std_output;

    return 0;
}

//CHECK_FILE:./inf.out
----- Expected Output (52 bytes)
inf
inf
inf
-nan
-nan
-nan
inf
inf
-inf
inf
T
F
F
F
----- Generated Output (49 bytes)
inf
inf
inf
nan
nan
nan
inf
inf
-inf
inf
T
F
F
F
-----------------------
    [FAIL] inf
  Subpackage passed 0 / 1
 Package passed 0 / 1
Toolchain passed 0 / 1

Invalid 0 / 1

quinnpham@Quinns-MacBook-Pro tests %
```

**Review by rcunrau — APPROVED** [review]
Thanks for the clarification - it's pretty tricky to review 116 files :-)

**Comment by rcunrau** [comment]
Looks like the diff is -nan vs nan, which is possibly platform dependent?
(although I'm not sure why it would be)

**Comment by JustinMeimar** [comment]
Made the `-nan` a seprate issue and made a new branch which does a rebase to clean up some of the messy commits. (~20 CI debuggings)

**Comment by JustinMeimar** [comment]
Made the `-nan` a seprate issue and made a new branch which does a rebase to clean up some of the messy commits. (~20 CI debuggings)

**Pull request closed without merging**
